FROM php:apache

WORKDIR /var/www/html/

COPY ./source /var/www/html/

RUN chown -R root:www-data /var/www/html && chmod 750 /var/www/html

RUN find . -type f -exec chmod 640 {} \;

RUN find . -type d -exec chmod 750 {} \;

RUN chmod +t -R /var/www/html/

RUN echo "PHOLAC{Th1s_1S_Fl3G_h3H5Ha}" >> /etc/passwd

EXPOSE 80
