FROM php:7.3-apache
WORKDIR /var/www/html/
COPY ./src .

RUN chown -R root:www-data /var/www/html && chmod 750 /var/www/html

RUN find . -type f -exec chmod 640 {} \;
RUN find . -type d -exec chmod 750 {} \;

RUN chmod +t -R /var/www/html/

