FROM php:7.3-apache

WORKDIR /var/www/html/

COPY ./src ./

RUN chown -R www-data:www-data /var/www/html && \
    chmod 750 /var/www/html

RUN find . -type f -exec chmod 640 {} \; && \
    find . -type d -exec chmod 750 {} \;

RUN chmod +t -R /var/www/html/

RUN echo "PHOLAC{Y3u_g0T_1He_F7a9}" >> /etc/passwd
